changelog:
  categories:
    - title: '🚀 Features'
      labels:
        - 'feat'
        - 'feature'
        - 'enhancement'
    - title: '🐛 Bug Fixes'
      labels:
        - 'fix'
        - 'bugfix'
        - 'bug'
    - title: '🧰 Maintenance'
      labels:
        - 'chore'
        - 'docs'
        - 'refactor'
    - title: '⚡ Performance'
      labels:
        - 'performance'
        - 'perf'
