name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clean Install Dependencies
        run: |
          npm ci || (rm -rf node_modules && npm install)
        env:
          CI: true

      - name: Build
        run: |
          # Clean and rebuild
          npm run clean
          rm -rf dist
          
          # Run build
          npm run build:prod
          
          # Debug directory contents
          echo "Current directory:"
          ls -la
          echo "Docs directory:"
          ls -la docs || true
          
          # Ensure docs directory has content
          if [ ! -f "docs/index.html" ]; then
            echo "Building failed - trying alternative build"
            npm run build
            if [ ! -f "docs/index.html" ]; then
              echo "Error: Build failed to produce index.html"
              exit 1
            fi
          fi
          
          # Copy for SPA routing
          cp docs/index.html docs/404.html
        env:
          CI: true

      - name: Create .nojekyll files
        run: |
          touch .nojekyll
          touch docs/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'deploy: update production build'
