name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clean Install Dependencies
        run: |
          npm ci || (rm -rf node_modules && npm install)
        env:
          CI: true

      - name: Build
        run: |
          # Remove old builds
          rm -rf .parcel-cache dist docs
          
          # Install additional needed transformer
          npm install -D @parcel/transformer-vue
          
          # Build with verbose output
          npx parcel build --target default --verbose
          
          # Debug output
          echo "Build complete, checking docs directory:"
          ls -la docs/ || true
          
          # Verify build output
          if [ ! -f "docs/index.html" ]; then
            echo "Trying alternative build path..."
            mkdir -p docs
            if [ -f "dist/index.html" ]; then
              cp -r dist/* docs/
            else
              echo "Error: No build output found"
              exit 1
            fi
          fi
          
          # Create 404 page
          cp docs/index.html docs/404.html
        env:
          CI: true
          NODE_ENV: production
          DEBUG: "parcel:*"

      - name: Create .nojekyll files
        run: |
          touch .nojekyll
          touch docs/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'deploy: update production build'
