name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clean Install Dependencies
        run: |
          npm ci || (rm -rf node_modules && npm install)
        env:
          CI: true

      - name: Build
        run: |
          # Debug environment
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          
          # Clean and prepare
          npm run clean
          mkdir -p docs
          
          # Create temporary parcel config
          echo '{
            "extends": "@parcel/config-default",
            "entries": ["index.html"],
            "distDir": "docs",
            "publicUrl": "./bead-puzzle-solver/"
          }' > .parcelrc-temp
          
          # Build with detailed output
          echo "Running production build..."
          NODE_ENV=production npx parcel build index.html \
            --config .parcelrc-temp \
            --no-cache \
            --no-optimize \
            --log-level verbose \
            --detailed-report
          
          # Verify build
          echo "Build contents:"
          ls -la docs/
          
          if [ ! -f "docs/index.html" ]; then
            echo "Build failed - trying alternative build"
            NODE_ENV=production npm run build:prod || exit 1
          fi
          
          # Copy for SPA routing
          cp docs/index.html docs/404.html || exit 1

        env:
          CI: true
          NODE_ENV: production
          DEBUG: "parcel:*"

      - name: Create .nojekyll files
        run: |
          touch .nojekyll
          touch docs/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'deploy: update production build'
