name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clean Install Dependencies
        run: |
          npm ci || (rm -rf node_modules && npm install)
        env:
          CI: true

      - name: Build
        run: |
          # Ensure clean state
          npm run clean
          
          # Create docs directory
          mkdir -p docs
          
          # Run build with verbose logging
          echo "Running production build..."
          npm run build:prod -- --log-level verbose
          
          # Check build output
          echo "Checking build output..."
          if [ -d "docs" ] && [ "$(ls -A docs)" ]; then
            echo "Build output:"
            ls -la docs/
          else
            echo "Error: docs directory is empty"
            exit 1
          fi
          
          # Copy for SPA routing if index.html exists
          if [ -f "docs/index.html" ]; then
            cp docs/index.html docs/404.html
          else
            echo "Error: index.html not found in docs/"
            exit 1
          fi
        env:
          CI: true
          NODE_ENV: production

      - name: Create .nojekyll files
        run: |
          touch .nojekyll
          touch docs/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'deploy: update production build'
